name: Python Code Quality

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ejecutar el codigo
        run: pytest test.py
        
      - name: Probar el codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
          
